## 📊 Telco Customer Churn Analysis

### 🧹 Data Cleaning & Understanding

#### 🎯 Objective
The goal of this notebook is to clean and prepare the dataset for analysis by handling missing values, correcting data types, and creating meaningful features.

#### ** Why Data Cleaning Matters? **
Real-world data is often messy and inconsistent. Proper cleaning ensures that the analysis is accurate, reliable, and meaningful.

> “Garbage in, garbage out” — poor data quality leads to poor insights.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

ModuleNotFoundError: No module named 'src'

### 📂 Load Dataset

We begin by loading the dataset and inspecting its structure.

In [205]:
df = pd.read_csv("/Users/hp/Documents/ASTU/CSEC_Projects/DataScience/telco-churn-analysis/data/raw/Telco_Customer_Churn_Dataset.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,AvgMonthlySpend
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,29.850000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,0,55.573529
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,54.075000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,40.905556
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,75.825000

#### 🔍 Initial Data Inspection

Understanding the dataset structure, data types, and completeness.

In [206]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   int64
 21  AvgMonthlySpend   7032 non-null   float64
dtypes: float64(3), int64(3), object(16)
memory usage: 1.2+ MB

In [207]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,AvgMonthlySpend
count,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000
mean,0.162400,32.421786,64.798208,2283.300441,0.265785,64.799424
std,0.368844,24.545260,30.085974,2266.771362,0.441782,30.185891
min,0.000000,1.000000,18.250000,18.800000,0.000000,13.775000
25%,0.000000,9.000000,35.587500,401.450000,0.000000,36.179891
50%,0.000000,29.000000,70.350000,1397.475000,0.000000,70.373239
75%,0.000000,55.000000,89.862500,3794.737500,1.000000,90.179560
max,1.000000,72.000000,118.750000,8684.800000,1.000000,121.400000

#### ⚠️ Missing Values Analysis

Checking for missing data to ensure reliability of analysis.

In [208]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
AvgMonthlySpend     0
dtype: int64

### 🔧 Data Type Correction

The `TotalCharges` column is incorrectly stored as a string. 
We convert it to numeric for accurate calculations.

In [209]:
# df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# --- Clean TotalCharges ---
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

Now the invalid values are converted to missing values to maintain consistency. we can check them now

In [210]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
AvgMonthlySpend     0
dtype: int64

In [211]:
# Check BEFORE mapping
print(df['Churn'].unique())

[0 1]

### 🧹 Handling Missing Values

Since missing values are minimal, we remove them to maintain dataset integrity.

In [212]:
# df = df.dropna()
df = df.dropna(subset=['TotalCharges', 'Churn'])

In [213]:
df['Churn'].dtype
df['Churn'].head(10)

0    0
1    0
2    1
3    0
4    1
5    1
6    0
7    0
8    1
9    0
Name: Churn, dtype: int64

In [214]:
df['Churn'].unique()

array([0, 1])

### 🔁 Removing Duplicate Records

Ensuring each customer appears only once.

In [215]:
df = df.drop_duplicates()

### 🔄 Encoding Categorical Data

Convert the churn column into numerical format for analysis.

In [224]:
# Clean text
df['Churn'] = df['Churn'].astype(str).str.strip().str.lower()

# Create numeric version (DO NOT overwrite original)
df['Churn_numeric'] = df['Churn'].map({'yes': 1, 'no': 0})
df['Churn_numeric'] = df['Churn_numeric'].fillna(0).astype(int)

In [217]:

# Check AFTER mapping
df['Churn'].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

### ⚙️ Feature Engineering

Creating a new metric: average monthly spend per customer.

In [218]:
df = df[df['tenure'] > 0]
df['AvgMonthlySpend'] = df['TotalCharges'] / df['tenure']

### ✅ Final Data Verification

Ensuring the dataset is clean and ready for analysis.

In [219]:
df.shape
df['Churn'].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [220]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
 21  AvgMonthlySpend   7032 non-null   float64
 22  Churn_numeric     0 non-null      float64
dtypes: float64(4), int64(2), object(17)
memory usage: 1.2+ MB

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,AvgMonthlySpend,Churn_numeric
count,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,0.0
mean,0.162400,32.421786,64.798208,2283.300441,64.799424,NaN
std,0.368844,24.545260,30.085974,2266.771362,30.185891,NaN
min,0.000000,1.000000,18.250000,18.800000,13.775000,NaN
25%,0.000000,9.000000,35.587500,401.450000,36.179891,NaN
50%,0.000000,29.000000,70.350000,1397.475000,70.373239,NaN
75%,0.000000,55.000000,89.862500,3794.737500,90.179560,NaN
max,1.000000,72.000000,118.750000,8684.800000,121.400000,NaN

#### 🎯 Summary of Data Cleaning

- Converted incorrect data types
- Handled missing values
- Removed duplicates
- Created a derived feature for deeper insights
##### 🚀 Outcome
The dataset is now clean, consistent, and ready for advanced analysis.
##### 💡 Key Insight
Data cleaning is a critical step in data science, as it directly impacts the quality and reliability of insights.

In [221]:
df.to_csv("/Users/hp/Documents/ASTU/CSEC_Projects/DataScience/telco-churn-analysis/data/raw/cleaned_telco.csv", index=False)

This is to save the cleaned dataset to ensure reproducibility and consistency across analysis stages

In [3]:
plt.savefig("../outputs/figures/tenure_vs_churn.png")

AttributeError: module 'matplotlib' has no attribute 'savefig'